export const produk = [
  {
    id: 1,
    img: '/produk/image 1.png',
    name: 'Dress Brown',
    sales: 200,
    feature: ['/produk/image 1.png', '/produk/image 4.png'],
    price: 150000,
    star: 5,
  },
  {
    id: 2,
    img: '/produk/image 2.png',
    name: 'Lemon Combi Shirt',
    sales: 200,
    feature: ['/produk/image 1.png', '/produk/image 4.png'],
    price: 150000,
    star: 2,
  },
  {
    id: 3,
    img: '/produk/image 3.png',
    name: 'Hills 3 Colors',
    sales: 200,
    feature: ['/produk/image 1.png', '/produk/image 4.png'],
    price: 150000,
    star: 3,
  },
  {
    id: 4,
    img: '/produk/image 4.png',
    name: 'Dress Navy',
    sales: 200,
    feature: ['/produk/image 1.png', '/produk/image 4.png'],
    price: 150000,
    star: 4,
  },
  {
    id: 5,
    img: '/produk/image 5.png',
    name: 'Jacket Desert Green',
    sales: 200,
    feature: ['/produk/image 1.png', '/produk/image 4.png'],
    price: 150000,
    star: 5,
  },
  {
    id: 6,
    img: '/produk/image 6.png',
    name: 'Wagon Warrior Black',
    sales: 200,
    feature: ['/produk/image 1.png', '/produk/image 4.png'],
    price: 150000,
    star: 2,
  },
  {
    id: 7,
    img: '/produk/image 7.png',
    name: 'Jacket Japan Round',
    sales: 200,
    feature: ['/produk/image 1.png', '/produk/image 4.png'],
    price: 150000,
    star: 3,
  },
  {
    id: 8,
    img: '/produk/image 8.png',
    name: 'Hoodie Motorcross',
    sales: 200,
    feature: ['/produk/image 1.png', '/produk/image 4.png'],
    price: 150000,
    star: 4,
  },
];
